### PR TITLE
feat: add `pull_description` to placeholders

### PR DESCRIPTION
**Pull request by jschmid1**
This allows the user to copy the original pull request description to the backported PR. This can be helpful if the body contains links to ticketing systems, related documents etc.

Example usage:

``` yaml
          pull_description: |-
            Automated backport to `${target_branch}`, triggered by a
label in #${pull_number}.

            Original Description:
            ${pull_description}
```

### CODE REVIEW

**Comment by korthout** [comment]
Thanks @jschmid1! I love the idea and implementation! 🚀 

Two small things:
- Let's rename this to `pull_description` to align with the placeholders that access data from the original pull request
- Let's adjust align the documentation about the placeholder with the others

**Comment by jschmid1** [comment]
done @korthout

**Review by korthout — APPROVED** [review]
Great contribution @jschmid1! 🙌 Thanks!

I've made a quick adjustment of the docs the way I like it 😄 I assume that's fine with you.

**Comment by korthout** [comment]
Released in [`v2.4.0`](https://github.com/korthout/backport-action/releases/tag/v2.4.0) 🎉

**Pull request merged**
