### PR TITLE
feat: generate output regarding backport result (#211)

### PR DESCRIPTION
**Pull request by alxgrk**
Referring to #211: write to Github Actions Output whether all backports were successful and break down that information by all extracted backport targets.

### CODE REVIEW

**Comment by korthout** [comment]
Tested with backport-action-test:

**Test case 1**: https://github.com/korthout/backport-action-test/actions/runs/3938252391/jobs/6736727661
- PR: https://github.com/korthout/backport-action-test/pull/216
- Backport run: https://github.com/korthout/backport-action-test/actions/runs/3938255243/jobs/6736733011
- Backport PR: https://github.com/korthout/backport-action-test/pull/217
Screen Shot 2023-01-17 at 11 23 31

**Test case 2**: https://github.com/korthout/backport-action-test/actions/runs/3938288648/jobs/6736804673
- PR: https://github.com/korthout/backport-action-test/pull/218
- Backport run: https://github.com/korthout/backport-action-test/actions/runs/3938291145/jobs/6736809956
- Backport PR: https://github.com/korthout/backport-action-test/pull/219
Screen Shot 2023-01-17 at 11 26 08

**Manual test (conflict)**: 
- PR: https://github.com/korthout/backport-action-test/pull/220
- Backport run: https://github.com/korthout/backport-action-test/actions/runs/3938368573/jobs/6736975244
- Failure comment: https://github.com/korthout/backport-action-test/pull/220#issuecomment-1385181076
Screen Shot 2023-01-17 at 11 34 54

**Review by korthout — APPROVED** [review]
🚀 This is a really cool contribution @alxgrk 🙇 Thanks so much for this! 

👍 I've successfully tested it with my E2E test project ([backport-action-test](https://github.com/korthout/backport-action-test)), and it works great!

To make it work, I needed to build a new distribution. I did this by locally running `npm ci && npm run all` in the root of this project. Doing so automatically is something I want to improve in the near future (see https://github.com/korthout/backport-action/issues/313).

🔧 We should still document this in the README, but this can be done in a new pull request. I'll open an issue for it. ❓ Would you be willing to contribute that as well?

**Comment by alxgrk** [comment]
@korthout , glad I could contribute & your tests were successful. 🙂 

Just to be sure, you published a new version, which will be consumed automatically, if no version is specified in the workflow using it? Because I don't see any new git tag or similar...

Regarding #319 , I will try to pick it up asap.

**Comment by korthout** [comment]
>Because I don't see any new git tag or similar...

@alxgrk I did not yet release a new version. I'd like to wait until #319 is completed.

I was considering spending some time on #314 this afternoon to see if I could release both new features as `v1.1.0` as I'll be out of the office next week. 

If you'd like to use your new version immediately, you could switch to `korthout/backport-action@main`.

**Comment by alxgrk** [comment]
Sounds good, please go ahead. 👍

**Comment by korthout** [comment]
@alxgrk I sadly did not find the time to do all the work I wanted. So I ended up just adding the outputs to the README.

Your feature is now available in `v1.1.0`, `v1.1`, `v1`, and `v1.next-preview`.

**Comment by alxgrk** [comment]
I feel you :sweat_smile: thank you very much for publishing it anyways :muscle:

**Pull request merged**
